### ISSUE TITLE
SPIKE: Research attacks against which server is most vulnerable

### ISSUE THREAD

**Issue by charlottekies** [RubySpeeders/US-Navy-Project#37]
### Question
- What attacks is the server most vulnerable to, and how can we mitigate them at the lowest cost? 

### Findings

1. DDoS attacks
2.

**Comment by RubySpeeders** [comment]
-no personal information in our database, so not as worried about this
-a real concern is DDoS -- overwhelming a server
-no financial problems, but would crash the server
-create a ticket: for permanent fix -- protect the server against DDoS attacks & rate limits, for now -- use IP addresses of devs
