### ISSUE TITLE
As a user, I want to see the image of the instrument

### ISSUE THREAD

**Issue by RubySpeeders** [RubySpeeders/US-Navy-Project#6]
* like the musicians, for now we can use images and save them as files in the project
* @cheesehero112 can I task you with finding the best photos of the percussion instruments? Since you are our percussion expert 🥇 
* the six instruments are: tenor drum, snare drum, bass drum, cymbals, and bass drum + cymbals

**Comment by cheesehero112** [comment]
I can do that. Did we agree on the background being white or transparent?

**Comment by RubySpeeders** [comment]
Let's go with white for now -- I'm thinking it will be easier to do that? But if transparent is easier, go with that.

**Comment by cheesehero112** [comment]
@RubySpeeders > Working on showing added images. I'm seeing this warning that I have to figure out. Also, in general, trying to learn how to custom style Material UI components. 
<img width="997" alt="Screenshot 2023-05-09 at 2 22 13 PM" src="https://github.com/RubySpeeders/US-Navy-Project/assets/102322200/011fd286-2e95-4aa3-ae42-4041e90257fc">

**Comment by RubySpeeders** [comment]
@cheesehero112 I think that error might be my fault! I would ignore it for now. Were you able to figure out styling?

**Comment by cheesehero112** [comment]
Ok - let me know if you have a good guess on how to fix the error. Re: styling - Not yet! I will look into it this week.

**Comment by cheesehero112** [comment]
@RubySpeeders @charlottekies > Just made a PR to address this ticket. Let me know if you have any questions or feedback!
